version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - agentic
  - AIAIAI
  - arktype
  - ayaka
  - deepdml
  - deepseek
  - Granularities
  - kizuna
  - lume
  - metas
  - moeru
  - neko
  - ollama
  - Speaches
  - unspeech
  - valibot
  - xenova
  - xsai
  - xsschema
ignoreWords: []
import: []
